//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DQBase.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ROLMENU))]
    public partial class MENU: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid IDMENU
        {
            get { return _iDMENU; }
            set
            {
                if (_iDMENU != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IDMENU' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iDMENU = value;
                    OnPropertyChanged("IDMENU");
                }
            }
        }
        private System.Guid _iDMENU;
    
        [DataMember]
        public Nullable<System.Guid> IDMENUPADRE
        {
            get { return _iDMENUPADRE; }
            set
            {
                if (_iDMENUPADRE != value)
                {
                    _iDMENUPADRE = value;
                    OnPropertyChanged("IDMENUPADRE");
                }
            }
        }
        private Nullable<System.Guid> _iDMENUPADRE;
    
        [DataMember]
        public Nullable<int> NIVELMENU
        {
            get { return _nIVELMENU; }
            set
            {
                if (_nIVELMENU != value)
                {
                    _nIVELMENU = value;
                    OnPropertyChanged("NIVELMENU");
                }
            }
        }
        private Nullable<int> _nIVELMENU;
    
        [DataMember]
        public string DESCRIPCIONMENU
        {
            get { return _dESCRIPCIONMENU; }
            set
            {
                if (_dESCRIPCIONMENU != value)
                {
                    _dESCRIPCIONMENU = value;
                    OnPropertyChanged("DESCRIPCIONMENU");
                }
            }
        }
        private string _dESCRIPCIONMENU;
    
        [DataMember]
        public string RUTA
        {
            get { return _rUTA; }
            set
            {
                if (_rUTA != value)
                {
                    _rUTA = value;
                    OnPropertyChanged("RUTA");
                }
            }
        }
        private string _rUTA;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<ROLMENU> ROLMENU
        {
            get
            {
                if (_rOLMENU == null)
                {
                    _rOLMENU = new TrackableCollection<ROLMENU>();
                    _rOLMENU.CollectionChanged += FixupROLMENU;
                }
                return _rOLMENU;
            }
            set
            {
                if (!ReferenceEquals(_rOLMENU, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_rOLMENU != null)
                    {
                        _rOLMENU.CollectionChanged -= FixupROLMENU;
                    }
                    _rOLMENU = value;
                    if (_rOLMENU != null)
                    {
                        _rOLMENU.CollectionChanged += FixupROLMENU;
                    }
                    OnNavigationPropertyChanged("ROLMENU");
                }
            }
        }
        private TrackableCollection<ROLMENU> _rOLMENU;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ROLMENU.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupROLMENU(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ROLMENU item in e.NewItems)
                {
                    item.MENU = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ROLMENU", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ROLMENU item in e.OldItems)
                {
                    if (ReferenceEquals(item.MENU, this))
                    {
                        item.MENU = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ROLMENU", item);
                    }
                }
            }
        }

        #endregion
    }
}
